# This is a basic workflow to help you get started with Actions
name: Build and Deploy
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ dev ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
          sed -i 's|https://cdn.jsdelivr.net/gh/pkuhollow/webhole@gh-pages/index.html|./index.html|g' build/*-*
          sed -i 's|https://cdn.jsdelivr.net/gh/pkuhollow/webhole@gh-pages/service-worker.js|./service-worker.js|g' build/*-*
          sed -i 's|"https://cdn.jsdelivr.net/gh/pkuhollow/webhole@gh-pages","/service-worker.js"|".","/service-worker.js"|' build/static/js/*.js
          sed -i 's|storage.googleapis.com/workbox-cdn/releases/4.3.1|cdn.jsdelivr.net/npm/workbox-cdn@4.3.1/workbox|g' build/service-worker.js

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: build # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
